owner: saveside
repo: status.savew.dev
sites:
  - name: honeypie
    url: https://honeypie.savew.dev    
    expectedStatusCodes:
      - 404
  - name: honeybee
    url: https://honeybee.savew.dev
    expectedStatusCodes:
      - 404
  - name: ai
    url: https://chat.savew.dev
  - name: main
    url: https://savew.dev
  - name: notes
    url: https://notes.savew.dev
  - name: helm
    url: https://helm.savew.dev
  - name: files
    url: https://files.savew.dev
status-website:
  cname: status.savew.dev 
  logoUrl: https://raw.githubusercontent.com/saveside/k8s/refs/heads/main/assets/honey-k8s.png
  themeUrl: https://status.savew.dev/honeybee.css
  name: savew.dev status
  introTitle: "**savew.dev** Health Status"
  introMessage: Status monitor for my websites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/saveside/k8s 
