owner: saveside
repo: status.savew.dev
sites:
  - name: honeypie
    url: https://honeypie.savew.dev    
    expectedStatusCodes:
      - 404
  - name: honeybee
    url: https://honeybee.savew.dev
    expectedStatusCodes:
      - 404
  - name: argo
    url: https://argo.savew.dev
  - name: ai
    url: https://chat.savew.dev
  - name: umami
    url: https://umami.savew.dev/dashboard
  - name: main
    url: https://savew.dev
  - name: notes
    url: https://notes.savew.dev
  - name: helm
    url: https://helm.savew.dev
  - name: ai
    url: https://ai.krea.to
  - name: vault
    url: https://vault.savew.dev

status-website:
  cname: status.savew.dev 
  logoUrl: https://raw.githubusercontent.com/kubernetes/kubernetes/refs/heads/master/logo/logo.png
  themeUrl: https://status.krea.to/catppuccin-mocha.css
  name: savew.dev status
  introTitle: "**savew.dev** Health Status"
  introMessage: Status monitor for my websites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/saveside/k8s 
